server:
  port: 8085
  

spring:
  application:
    name: customer-microservice
  profiles:
    active: local

      
 
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8081/eureka
      #defaultZone: http://eurekaserver.local.pcfdev.io


feign:
   hystrix:
      enabled: false
            
      
hystrix:
  command:
    default:
       execution: 
          timeout:
             enabled: false

            
